### PR TITLE
Aph/boltify

### PR DESCRIPTION
**Pull request by m0dular**

### CODE REVIEW

**Comment by timidri** [comment]
@m0dular @kamiolszewski has determined the list of PE versions to test the boltified version on:
* 2016.4
* 2016.2
* 2015.3
* 3.8

I will start with 2016.4 and go back in time from there.

**Comment by timidri** [comment]
## 2016.4.10 test results

Executed on a local Vagrant machine, CentOS 7, 2 cores, 8GB RAM

1. The `pe_tech_check::configure` task runs without issues
1. The `pe_tech_check:collect` task errors out if no `/etc/puppetlabs/license.key` file is present. 
Log: https://gist.github.com/timidri/e2eaf92b0a6fb59c03c87ad0b4be6559 . 
If PTC should not support cases where the customer is using a complimentary 10 node license which doesn't require a license file, a friendlier error message (e.g. 'Unlicensed PE Masters cannot be checked with Puppet Tech Check') would be better.
1. The `pe_tech_check:collect` task errors out if the ticket number passed to the task doesn't comply with the ticket number format. The error message is misleading.
Log: https://gist.github.com/timidri/256a3bebbc18c1337632d21a88400108
1. The `pe_tech_check:collect` task finishes without issues if the ticket number given is '12345', log: https://gist.github.com/timidri/3cf9ead17c7b517cd450df164012231c
result file: [puppet_enterprise_support_12345_master_20190613133951.tar.gz](https://github.com/puppetlabs/pe_tech_check/files/3286447/puppet_enterprise_support_12345_master_20190613133951.tar.gz)

**Comment by timidri** [comment]
I will proceed testing on older versions as soon as I am able to spin up PE Masters with those versions. My first attempt of spinning up a 2015.3.3 master in AWS failed because of an installation issue, probably related to the fact that I'm using an AWS EC2 instance. 
Errors I am hitting:
```
Error: Could not start Service[pe-console-services]: Execution of '/bin/systemctl start pe-console-services' returned 1: Job for pe-console-services.service failed because the control process exited with error code. See "systemctl status pe-console-services.service" and "journalctl -xe" for details.
```
and
```
2019-06-13 14:17:28,803 ERROR [c.j.b.PoolWatchThread] Error in trying to obtain a connection. Retrying in 7000ms
org.postgresql.util.PSQLException: The hostname ip-172-31-2-196.eu-west-2.compute.internal could not be verified.
```
The hostname `ip-172-31-2-196.eu-west-2.compute.internal` is valid, but I am assuming puppetdb requires the hostname to be in /etc/hosts or equal to the certname or some other interesting restriction? Any pointers appreciated.

**Comment by m0dular** [comment]
Thanks for testing it.  For the 2016.4 results that failed, it shouldn't be the case that a missing license file causes the whole thing to fail.  It just runs the `grep` without checking the return code:

```
grep -i -v UUID /etc/puppetlabs/license.key
```
I spun up a 2016.4 box in vmpooler and I was able to run it without a license file.

The `Error running support script` message should only happen when the script can't find the `.tar.gz` created by the support script.  This does raise the issue that I'm not returning `stderr` from `puppet enterprise support`, so it's not completely clear why that failed in this case.  I'll fix that.

I do see something in the runs that failed:

```
Unknown Infrastructure Error: Unable to find a Primary Master via a PuppetDB query Error
```

Could it be the case that you still needed to run `puppet agent -t` until there were no more changes after you spun up this box?  I don't see this message in the successful tarball.

As for older versions, I usually spin something up in vmpooler and grab an installer from `http://getpe.delivery.puppetlabs.net`.

**Comment by m0dular** [comment]
I also think that 2015.x will probably fail since the command to run the support script is different.  I'll have to add a version check and adjust accordingly.

**Comment by timidri** [comment]
@m0dular I have re-run the collect task on a freshly built Vagrant box with PE 2016.4.10 and it has now succeeded, see attachment for the resulting tarball.
[puppet_enterprise_support_12345_master_20190614092858.tar.gz](https://github.com/puppetlabs/pe_tech_check/files/3290003/puppet_enterprise_support_12345_master_20190614092858.tar.gz)

**Comment by timidri** [comment]
@m0dular FYI: unfortunately the link you mentioned doesn't have the 2015.3.3 version. I'm downloading it from https://pe-builds.s3.amazonaws.com/released/2015.3.3

**Comment by timidri** [comment]
# 2016.3.3 test results
@m0dular As you already mentioned, the collect task errors out. Let me know when you update the PR with the version check so I can continue my testing.

**Comment by m0dular** [comment]
@timidri Sorry for the delay, been busy over here.  I pushed a new commit that gets the version and runs the older support script command if needed.  I decided to skip 3.x compatibility; if anyone tries a health check on that version, that's all we need to know.

I tested it on a few older versions and it did work, but we get less information back.  `pe tune` doesn't seem to work on old versions, for example.

**Comment by timidri** [comment]
> @timidri Sorry for the delay, been busy over here. I pushed a new commit that gets the version and runs the older support script command if needed. I decided to skip 3.x compatibility; if anyone tries a health check on that version, that's all we need to know.
> 
> I tested it on a few older versions and it did work, but we get less information back. `pe tune` doesn't seem to work on old versions, for example.

@m0dular Great, thanks for the update. I gather I don't need to retest then?

**Comment by m0dular** [comment]
I think another person testing it would be better, if you have time available.  Thanks!

**Comment by timidri** [comment]
# 2016_2_1 test results
Performed on vmpooler centos-7-x86_64 host (2 cores, 6GB RAM)
Both tasks completed without issues.
Result file: 
[2016_2_1_puppet_enterprise_support_qa12zxgkqkp3ewr_20190628150126.tar.gz](https://github.com/puppetlabs/pe_tech_check/files/3339748/2016_2_1_puppet_enterprise_support_qa12zxgkqkp3ewr_20190628150126.tar.gz)

**Comment by timidri** [comment]
# 2016_4_15 test results
Performed on vmpooler centos-7-x86_64 host (2 cores, 6GB RAM)
Both tasks completed without issues.
Result file:
[2016_4_15_puppet_enterprise_support_HCL_wd7bk2283qbs9rs_20190628115537.tar.gz](https://github.com/puppetlabs/pe_tech_check/files/3339753/2016_4_15_puppet_enterprise_support_HCL_wd7bk2283qbs9rs_20190628115537.tar.gz)

**Comment by timidri** [comment]
@m0dular I've completed testing on 2015.3.3, 2016.2.1 and did an extra 2016.4.15 (latest z) for good measure. The test results are above in separate comments, with result files attached.

**Pull request merged**
